### ISSUE TITLE
Duplicated wildtype scores or counts

### ISSUE THREAD

**Issue by JamesFrifan** [VariantEffect/mavehgvs#11]
Some MAVE studies use shotgun method for sequencing which will lead to multiple non-substitution (represented like wildtype) scores or counts for each protein residue.

The figure is an example from Giacomelli et al., 2018 in which case the last column is showing the counts for three non-substituted codons.

These entries can be annotated as: c.1_3=, c.4_6= & c.7_9= and mavehgvs should be able to support them.

<img width="983" alt="image" src="https://user-images.githubusercontent.com/48193804/109782663-3cdf4500-7c5d-11eb-9304-f7aaa56c2dd5.png">

**Comment by afrubin** [comment]
Addressed by https://github.com/VariantEffect/mavehgvs/pull/14
